-- AlterTable
ALTER TABLE `users` ADD COLUMN `authProvider` ENUM('LOCAL', 'GOOGLE', 'FACEBOOK', 'GITHUB') NOT NULL DEFAULT 'LOCAL',
    ADD COLUMN `dateOfBirth` DATETIME(3) NULL,
    ADD COLUMN `phone` VARCHAR(191) NULL;
